name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set the value
      id: step_one
      run: |
       echo "tag=$(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | jq -r .tag_name)" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: |
       echo "${{ env.tag }}" # This will output 'yellow'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
